using BepInEx;
using HarmonyLib;
using Jotunn.Managers;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.crafting;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.farming;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.fletching;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.herblore;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.slayer;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.impl.smithing;
using ScapeHeimModStub.com.scapeheim.entity.player.skill.skillunlockpopups;
using System.Collections.Generic;
using UnityEngine;
namespace ScapeHeimModStub.com.scapeheim.entity.player.skill.skillunlockpopups
{
    [HarmonyPatch(typeof(Player))]
    public static class SkillLevelUnlockPatch
    {
        private static readonly Dictionary<Skills.SkillType, float> PreviousLevels = new();
        private static readonly Dictionary<string, Sprite> CachedRenderedIcons = new(); // Custom prefab icons generated by jotunn for xp popups other than items

        [HarmonyPatch(nameof(Player.RaiseSkill))]
        [HarmonyPrefix]
        private static void Prefix(Player __instance, Skills.SkillType skill)
        {
            PreviousLevels[skill] = __instance.GetSkillLevel(skill);
        }

        [HarmonyPatch(nameof(Player.RaiseSkill))]
        [HarmonyPostfix]
        private static void Postfix(Player __instance, Skills.SkillType skill)
        {

            if (!PreviousLevels.TryGetValue(skill, out float oldLevel))
            {
                return;
            }

            int before = Mathf.FloorToInt(oldLevel);
            int after = Mathf.FloorToInt(__instance.GetSkillLevel(skill));

            if (after <= before)
            {
                return;
            }

            if (skill == FletchingSkill.Type) // Fletching
            {

                foreach (var unlock in FletchingData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Fletching unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Fletching");
                }
            }
            else if (skill == SlayerSkill.Type) // Slayer
            {

                foreach (var unlock in SlayerData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Slayer unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Slayer");
                }
            }
            else if (skill == SmithingSkill.Type) // Smithing
            {

                foreach (var unlock in SmithingData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Smithing unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Smithing");
                }
            }
            else if (skill == Skills.SkillType.Crafting) // Crafting
            {

                foreach (var unlock in CraftingData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Crafting unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Crafting");
                }
            }
            else if (skill == HerbloreSkill.Type) // Herblore
            {

                foreach (var unlock in HerbloreData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Herblore unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Herblore");
                }
            }
            else if (skill == Skills.SkillType.Farming) // Farming
            {
                foreach (var unlock in FarmingData.GetUnlocksForLevel(after))
                {
                    Jotunn.Logger.LogInfo($"[SkillDebug] Farming unlock: {unlock.ItemId}");
                    ShowUnlock(unlock.ItemId, "Farming");
                }
            }
            else
            {
                Jotunn.Logger.LogInfo($"[SkillDebug] Unhandled skill: {skill}");
            }
        }

        private static void ShowUnlock(string name, string skillName)
        {
            ObjectDB db = ObjectDB.instance;
            ZNetScene scene = ZNetScene.instance;

            if (db == null || scene == null)
            {
                Jotunn.Logger.LogWarning("[SkillUnlock] DB or Scene not ready");
                return;
            }

            GameObject prefab =
                db.GetItemPrefab(name) ??
                scene.GetPrefab(name);

            if (prefab == null)
            {
                Jotunn.Logger.LogWarning($"[SkillUnlock] Missing prefab in BOTH systems: {name}");
                return;
            }

            Sprite icon = null;
            string niceName = name;

            // farming override
            if (skillName == "Farming")
            {
                niceName = FarmingData.GetDisplayName(name, niceName);
            }

            ItemDrop itemDrop = prefab.GetComponent<ItemDrop>();
            if (itemDrop != null)
            {
                icon = itemDrop.m_itemData.GetIcon();
                niceName = Localization.instance != null
                    ? Localization.instance.Localize(itemDrop.m_itemData.m_shared.m_name)
                    : itemDrop.m_itemData.m_shared.m_name;
            }
            else
            {
                Character character = prefab.GetComponent<Character>();

                if (character != null)
                {
                    niceName = Localization.instance != null
                        ? Localization.instance.Localize(character.m_name)
                        : character.m_name;
                }

                // rendered prefab icon cache
                CachedRenderedIcons.TryGetValue(name, out icon);

                // fallback if render failed
                if (icon == null)
                {
                    icon = GetSkillFallbackIcon(skillName);
                }
            }

            if (icon == null)
            {
                // fallback safety icon (prevents empty UI)
                Jotunn.Logger.LogWarning($"[SkillUnlock] No icon for {name}");
            }

            SkillUnlockPopup.Show(
                icon,
                $"Congratulations, you unlocked {niceName} from the {skillName} skill!"
            );
        }

        private static Sprite GetSkillFallbackIcon(string skillName)
        {
            if (skillName == "Slayer")
                return SlayerSkill.Instance?.Icon;

            return null;
        }

        public static void Init(BaseUnityPlugin plugin)
        {
            PrefabManager.OnVanillaPrefabsAvailable += () =>
            {
                BuildRenderedIconCache(plugin);
            };
        }

        private static void BuildRenderedIconCache(BaseUnityPlugin plugin)
        {
            HashSet<string> prefabsToRender = new();

            // Slayer
            foreach (var entry in SlayerData.Data.Values)
            {
                prefabsToRender.Add(entry.ItemId);
            }

            // Farming
            foreach (var entry in FarmingData.Data.Values)
            {
                prefabsToRender.Add(entry.ItemId);
            }

            // Future skills can add their prefab names here later

            foreach (string prefabName in prefabsToRender)
            {
                try
                {
                    GameObject prefab =
                        PrefabManager.Instance.GetPrefab(prefabName);

                    if (prefab == null)
                    {
                        Jotunn.Logger.LogWarning(
                            $"[ScapeHeim] Missing prefab for icon render: {prefabName}"
                        );

                        continue;
                    }

                    // items already have icons
                    if (prefab.GetComponent<ItemDrop>() != null)
                    {
                        continue;
                    }

                    RenderManager.RenderRequest request =
                        new RenderManager.RenderRequest(prefab);

                    request.Rotation = RenderManager.IsometricRotation;
                    request.UseCache = true;
                    request.TargetPlugin = plugin.Info.Metadata;

                    Sprite icon = RenderManager.Instance.Render(request);

                    if (icon != null)
                    {
                        CachedRenderedIcons[prefabName] = icon;
                    }
                }
                catch (System.Exception ex)
                {
                    Jotunn.Logger.LogWarning(
                        $"[ScapeHeim] Failed rendering icon for {prefabName}: {ex}"
                    );
                }
            }

            Jotunn.Logger.LogInfo(
                $"[ScapeHeim] Cached {CachedRenderedIcons.Count} rendered prefab icons"
            );
        }
    }
}